Reduce OBJECTLIMIT to prevent files from exceeding max size
Since NCBI has file size limits, ideally our file writer would split based on output size rather than number of entries, but for now this will address the problem.

Received email from NCBI:

> The following LinkOut file you recently sent contains critical error(s) that prevents us from processing the files.
>
> sequencelinkout12.xml    37150398    2014-09-09,01:15:12
>
> Error:  Maximal file size limit exceeded: 37150398 bytes instead of 33214400 bytes permitted
>
> Please correct the errors and resend the file.